export type ButtonVariant = 'default' | 'expand' | 'disabled' | 'disabled-default' | 'blue'
export type SectionVariant = 'default' | 'blue'

export const buttonDefaultStyle: ButtonVariant = 'default'
export const buttonExpandStyle: ButtonVariant = 'expand'
export const buttonDisableStyle: ButtonVariant = 'disabled'
export const buttonDisableDefaultStyle: ButtonVariant = 'disabled-default'
export const buttonBlueStyle: ButtonVariant = 'blue'
export const sectionDefaultStyle: SectionVariant = 'default'
export const sectionBlueStyle: SectionVariant = 'blue'
export const sectionNoPadStyle: SectionVariant = 'default'
