// One-shot migration: parse the JSX SVG icons in react-viewers/icons.tsx into
// framework-neutral data at src/vim-web/icons/iconData.ts, rendered by both the
// DOM layer (icons/svg.ts) and React (react-viewers/icons.tsx).
//   node scripts/extract-icons.mjs
import { readFileSync, writeFileSync } from 'fs'
import { dirname, join } from 'path'
import { fileURLToPath } from 'url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const src = readFileSync(join(root, 'src/vim-web/react-viewers/icons.tsx'), 'utf8')
const out = join(root, 'src/vim-web/icons/iconData.ts')

// One chunk per `export function`; splitting on the declaration cannot merge neighbours.
const chunks = src.split(/(?=^export function )/m)
const svgRe = /<svg[\s\S]*<\/svg>/
// Tags and attributes may span lines; values are either "literal" or {prop}.
const tagRe = /<(\/?)([a-zA-Z][\w:-]*)([^>]*?)(\/?)>/g
const attrRe = /([a-zA-Z_:][\w:.-]*)\s*=\s*(?:"([^"]*)"|\{(\w+)\})/g

function parse (xml) {
  const top = { children: [] }
  const stack = [top]
  let m
  while ((m = tagRe.exec(xml))) {
    const [, close, tag, rawAttrs, selfClose] = m
    if (close) { stack.pop(); continue }
    const attrs = {}
    let a
    while ((a = attrRe.exec(rawAttrs))) {
      const [, name, literal, prop] = a
      attrs[name] = literal !== undefined ? literal : '$' + prop
    }
    const node = { tag, attrs, children: [] }
    stack[stack.length - 1].children.push(node)
    if (!selfClose) stack.push(node)
  }
  if (top.children.length !== 1) throw new Error('expected exactly one <svg>, got ' + top.children.length)
  return top.children[0]
}

// Keep geometry/paint attributes; drop editor junk. '$fill' is the caller-supplied fill.
function clean (nodes) {
  return nodes.map(n => {
    const attrs = { ...n.attrs }
    delete attrs['data-name']
    const o = { tag: n.tag, attrs }
    if (n.children.length) o.children = clean(n.children)
    return o
  })
}

const icons = {}
const stats = {}
const count = nodes => nodes.forEach(n => { stats[n.tag] = (stats[n.tag] ?? 0) + 1; count(n.children ?? []) })
for (const chunk of chunks) {
  const head = chunk.match(/^export function (\w+)/)
  if (!head) continue
  const name = head[1]
  const xml = chunk.match(svgRe)?.[0]
  if (!xml) { console.warn('no <svg> in', name); continue }
  const svg = parse(xml)
  const def = { viewBox: svg.attrs.viewBox }
  if (svg.attrs.fill === '$fill') def.fill = '$fill'
  def.children = clean(svg.children)
  count(def.children)
  icons[name] = def
}

const ts = `// GENERATED by scripts/extract-icons.mjs from the original JSX icon set — do not edit by hand.
// Framework-neutral SVG icon data, rendered by src/vim-web/icons/svg.ts (DOM) and
// src/vim-web/react-viewers/icons.tsx (React). '$fill' marks the caller-supplied fill.
import type { IconDef } from './types'

export const iconData = ${JSON.stringify(icons, null, 2)} satisfies Record<string, IconDef>

export type IconName = keyof typeof iconData
export const iconNames = Object.keys(iconData) as IconName[]
`
if (!Object.keys(icons).length) throw new Error("no icons found: icons.tsx is no longer the JSX source; iconData.ts is the source of truth now")
writeFileSync(out, ts)
console.log('icons:', Object.keys(icons).length, '| nodes:', JSON.stringify(stats))
console.log('names:', Object.keys(icons).join(' '))
