// One-shot generator for src/vim-web/icons/iconData.ts.
//
//   node scripts/generate-icons.mjs
//
// Redraws the icon set from Fluent UI System Icons (MIT), Microsoft's successor to the Segoe MDL2
// glyph font VIM Flex uses. We cannot use MDL2 itself: it is an OS font, so the codepoints would be
// tofu on any non-Windows browser, and its licence covers neither non-Microsoft platforms nor
// redistribution to third parties (see styles/fonts/Segoe_EULA.txt in the design system). Fluent
// shares MDL2's design language and ships as plain SVG, so the viewer reads like Flex without the
// font.
//
// Every icon comes from the 20px regular weight, which gives one optical weight across the set
// (the hand-drawn originals mixed 256, 50 and 20 unit grids). Names are ours and stay put — they
// are public API; only the artwork changes. A name whose meaning Fluent has no word for takes the
// nearest primitive of the same family, which is what Flex does with MDL2.
import { readFileSync, writeFileSync } from 'fs'
import { dirname, join } from 'path'
import { fileURLToPath } from 'url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const ICONS = join(root, 'node_modules/@fluentui/svg-icons/icons')
const OUT = join(root, 'src/vim-web/icons/iconData.ts')

/** our name -> Fluent basename (the `_20_regular.svg` is added below). */
const MAP = {
  // Pointer and chrome
  pointer: 'cursor',
  filter: 'filter',
  slidersHoriz: 'options',
  settings: 'settings',
  help: 'question_circle',
  trash: 'delete',
  checkmark: 'checkmark',
  undo: 'arrow_undo',
  closeIcon: 'dismiss',
  home: 'home',
  fullScreen: 'full_screen_maximize',
  minimize: 'full_screen_minimize',
  treeView: 'text_bullet_list_tree',
  more: 'more_horizontal',
  menu: 'line_horizontal_3',
  collapse: 'chevron_down',
  chevronUp: 'chevron_up',
  arrowLeft: 'chevron_left',
  fullArrowLeft: 'arrow_left',

  // Visibility
  visible: 'eye',
  hidden: 'eye_off',
  showAll: 'eye_lines',
  showSelection: 'eye',
  hideSelection: 'eye_off',
  ghost: 'layer_diagonal',
  ghostDead: 'square_eraser',

  // Camera
  frameScene: 'arrow_fit',
  frameSelection: 'target',
  frameRect: 'resize',
  autoCamera: 'camera',
  camera: 'camera',
  orbit: 'cube_rotate',
  look: 'eye_tracking',
  perspective: 'cube',
  orthographic: 'square',
  pan: 'hand_right',
  zoom: 'zoom_in',

  // Isolation. Flex rotates a square glyph into a diamond for this; Fluent has the diamond itself.
  isolateSelection: 'diamond',
  autoIsolate: 'diamond',
  toggleIsolation: 'diamond_dismiss',

  // Tools
  measure: 'ruler',

  // Section box. Flex uses one glyph family here too, varied by what the press does.
  sectionBox: 'cube',
  sectionBoxVisible: 'cube',
  sectionBoxAuto: 'cube',
  sectionBoxDisable: 'square_dismiss',
  sectionBoxSettings: 'options',
  sectionBoxClip: 'crop',
  sectionBoxIgnore: 'square_hint',
  sectionBoxReset: 'arrow_reset',
  sectionBoxShrink: 'resize_small',
  sectionBoxShrink2: 'arrow_minimize'
}

/** Attributes worth keeping off a Fluent path. `fill` is dropped: the root carries the caller's. */
const KEEP = ['d', 'fill-rule', 'clip-rule']

function readIcon (base) {
  const file = join(ICONS, `${base}_20_regular.svg`)
  const svg = readFileSync(file, 'utf8')
  const viewBox = /viewBox="([^"]+)"/.exec(svg)?.[1]
  if (!viewBox) throw new Error(`no viewBox in ${file}`)

  const children = []
  for (const tag of svg.matchAll(/<path\b([^>]*)\/?>/g)) {
    const attrs = {}
    for (const attr of tag[1].matchAll(/([a-zA-Z-]+)="([^"]*)"/g)) {
      if (KEEP.includes(attr[1])) attrs[attr[1]] = attr[2]
    }
    if (attrs.d) children.push({ tag: 'path', attrs })
  }
  if (!children.length) throw new Error(`no paths in ${file}`)
  return { viewBox, fill: '$fill', children }
}

const data = {}
for (const [name, base] of Object.entries(MAP)) data[name] = readIcon(base)

const header = `// GENERATED by scripts/generate-icons.mjs from Fluent UI System Icons (MIT) — do not edit by hand.
// Framework-neutral SVG icon data, rendered by src/vim-web/icons/svg.ts. The root carries the
// caller's fill ('$fill'); the paths inherit it.
import type { IconDef } from './types'

export const iconData = `

const footer = ` satisfies Record<string, IconDef>

export type IconName = keyof typeof iconData
export const iconNames = Object.keys(iconData) as IconName[]
`

writeFileSync(OUT, header + JSON.stringify(data, null, 2) + footer, 'utf8')
console.log(`wrote ${Object.keys(data).length} icons to ${OUT}`)
