on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Skip workflow if triggered by itself
        if: ${{ contains(github.event.head_commit.message, '[ci-skip]') }}
        run: echo "Skipping this workflow run."

      - name: Build Pages
        run: build:website
